#!/bin/bash
# Quick Reference: Hard-Negative Mining Results & Next Steps

echo "=== Phase 1.2 Hard-Negative Mining: Complete ✅ ==="
echo ""
echo "📊 Results:"
echo "  • Candidates Extracted: 17,957 frames"
echo "  • Videos Processed: 406"
echo "  • JPEG Storage: ~9.6 GB"
echo "  • Phase 1.1 Pass Rate: 100%"
echo "  • Avg YOLO Confidence: 0.874"
echo "  • Avg Fused Confidence: 0.743"
echo ""
echo "📁 Location:"
echo "  • Merged CSV: outputs/hardneg_mining/candidates_master.csv"
echo "  • GPU0 JPEGs: outputs/hardneg_mining_gpu0/candidates/ (5.0 GB, 9,258 frames)"
echo "  • GPU1 JPEGs: outputs/hardneg_mining_gpu1/candidates/ (4.6 GB, 8,701 frames)"
echo ""
echo "🚀 Quick Start: Visual Review"
echo ""
echo "1️⃣  Get Statistics:"
echo "   source .venv/bin/activate"
echo "   python scripts/sample_candidates.py"
echo ""
echo "2️⃣  Interactive Review (one-by-one):"
echo "   python scripts/review_hard_negatives.py --mode interactive --sample-size 100"
echo ""
echo "3️⃣  Bulk Export by Score Range:"
echo "   python scripts/review_hard_negatives.py --mode export \\"
echo "     --score-range 0.55 0.65 --category orange_trucks --max-per-cat 50"
echo ""
echo "4️⃣  Generate Manifest:"
echo "   python scripts/review_hard_negatives.py --mode manifest"
echo ""
echo "📖 Full Documentation:"
echo "   • HARD_NEGATIVES_SUMMARY.md (overview + categorization strategy)"
echo "   • PHASE1_2_MINING_REPORT.md (detailed statistics + analysis)"
echo ""
echo "💡 Recommendation:"
echo "   Start with: python scripts/sample_candidates.py"
echo "   Then try:  python scripts/review_hard_negatives.py --mode interactive --sample-size 50"
echo ""
